services:
  bookmarker-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
    ports:
      - "15433:5432"  # Changed from 15432 to 15433

  bookmarker-api:
    build:
      context: bookmarker-api
      dockerfile: Dockerfile.layered
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATABASE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookmarker-db:5432/appdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "18080:8080"
    restart: always
    depends_on:
      - bookmarker-db
